table departments {

id int
department_name varchar
loacotion varchar
created_at timestamp
}



table patients {

id int 
first_name varchar
last_name varchar
adress text 
phone varchar
email varchar
date_of_birth date
created_at timestamp
updated_at timestamp
user_id int
}

table doctors {

id int 
first_name varchar
last_name varchar
specialisation varchar
phone varchar
email varchar
department_id int
created_at timestamp
updated_at timestamp
user_id int

}
ref: doctors.department_id > departments.id


table  Medications {

id int
name varchar(255)
instruction text
created_at timestamp

}

table Prescription {

id int 
date date 
doctor_id int 
patient_id int 
Medication_id int
dosage_instructions text
created_at timestamp
}

ref: Prescription.Medication_id >Medications.id
ref: Prescription.doctor_id > doctors.id
ref: Prescription.patient_id > patients.id


table Appointment {

id int
date date
time time
doctor_id int 
patient_id int
reason text
ststus enum(scheduled, done, cancelled)
created_at timestamp
updated_at timestamp

}
ref: Appointment.doctor_id > doctors.id
ref: Appointment.patient_id > patients.id


